name: Publish to NPM

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    uses: sendo-labs/reusable-workflows/.github/workflows/npm-publish.yml@v1.0.0
    with:
      bun-version: 'latest'
      node-version: '22'
      working-directory: '.'
      registry-url: 'https://registry.npmjs.org'
      skip-tests: false
      skip-build: false
      access: 'public'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}